### ISSUE TITLE
license changed: 2-clause BSD license

### ISSUE THREAD

**Issue by a-teammate** [lasote/conan-nasm-installer#1]
They changed their license.
see http://www.nasm.us/

**Comment by lasote** [comment]
Should be changed with "Simplified (2-clause) BSD license"?

**Comment by a-teammate** [comment]
According to https://opensource.org/licenses/BSD-2-Clause its "2-Clause BSD License" as the main name and its SPDX short identifier: "BSD-2-Clause"

**Comment by lasote** [comment]
Mhhh, but it's what it's filled in the "license" field of my recipe, right? https://github.com/lasote/conan-nasm-installer/blob/master/conanfile.py

Maybe you've looked to the LICENSE file of my repository, that is the license for the recipe, not for the library.

**Comment by a-teammate** [comment]
Ups Shit, I thought I double checked it.  
Obviously not.  
No, I got confused by the "License" part on https://bintray.com/conan-community/conan/nasm%3Aconan ..

Personally I think all recipe contributions to conan-center should either be covered by an uniform license or at least that license shouldn't require an acknowledgement in the end products documentation/readme/installer.
However this issue was solely opened by mistake so I'll close it :)

**Comment by lasote** [comment]
OK! now I understand, thanks for opening the issue. I've fixed the license on Bintray.
